package:
  name: cookiecutter
  version: "1.0.0"

source:
  fn: cookiecutter-1.0.0.tar.gz
  url: https://pypi.python.org/packages/source/c/cookiecutter/cookiecutter-1.0.0.tar.gz
  md5: 4174591b310812a6e61cfea9655c3c6f
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - cookiecutter = cookiecutter:main
    #
    # Would create an entry point called cookiecutter that calls cookiecutter.main()

    - cookiecutter = cookiecutter.cli:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - binaryornot >=0.2.0
    - jinja2 >=2.7
    - pyyaml >=3.10
    - click <4.0
    - mock

  run:
    - python
    - binaryornot >=0.2.0
    - jinja2 >=2.7
    - pyyaml >=3.10
    - click <4.0
    - mock

test:
  # Python imports
  imports:
    - cookiecutter

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - cookiecutter --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - pytest
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/audreyr/cookiecutter
  license: BSD License
  summary: 'A command-line utility that creates projects from project templates, e.g. creating a Python package project from a Python package project template.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
